# Generated by Django 4.0.3 on 2022-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircond1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('t1', models.SmallIntegerField(blank=True, null=True)),
                ('t2', models.SmallIntegerField(blank=True, null=True)),
                ('t3', models.SmallIntegerField(blank=True, null=True)),
                ('t4', models.SmallIntegerField(blank=True, null=True)),
                ('t5', models.SmallIntegerField(blank=True, null=True)),
                ('pressure', models.SmallIntegerField(blank=True, null=True)),
                ('c1', models.SmallIntegerField(blank=True, null=True)),
                ('c2', models.SmallIntegerField(blank=True, null=True)),
                ('current', models.SmallIntegerField(blank=True, null=True)),
                ('client_login', models.CharField(max_length=255)),
            ],
        ),
    ]
