# Generated by Django 4.0.3 on 2022-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircond', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aircond1',
            new_name='AircondData',
        ),
    ]
