# Generated by Django 4.0.3 on 2022-03-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aircond', '0002_rename_aircond1_airconddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconddata',
            name='client_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
