# Generated by Django 4.0.3 on 2022-03-13 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircondData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('t1', models.SmallIntegerField(blank=True, null=True)),
                ('t2', models.SmallIntegerField(blank=True, null=True)),
                ('t3', models.SmallIntegerField(blank=True, null=True)),
                ('t4', models.SmallIntegerField(blank=True, null=True)),
                ('t5', models.SmallIntegerField(blank=True, null=True)),
                ('pressure', models.SmallIntegerField(blank=True, null=True)),
                ('c1', models.SmallIntegerField(blank=True, null=True)),
                ('c2', models.SmallIntegerField(blank=True, null=True)),
                ('current', models.SmallIntegerField(blank=True, null=True)),
                ('client_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
