# Generated by Django 4.0.3 on 2022-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconddata',
            name='cond_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
