# Generated by Django 4.0.3 on 2022-03-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_airconddata_airconds_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconddata',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='airconddata',
            name='c2',
        ),
    ]
