# Generated by Django 4.0.3 on 2022-03-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_airconddata_c1_remove_airconddata_c2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airconddata',
            old_name='client_login',
            new_name='client_login_id',
        ),
    ]
