# Generated by Django 4.0.3 on 2022-03-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_airconddata_delete_clientairconddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airconddata',
            old_name='client_id',
            new_name='client',
        ),
    ]
