BROKER_ADDRESS = '194.58.96.174'
BROKER_PORT = 1883
BROKER_LOGIN = 'kr_broker'
BROKER_PASSWORD = 'j%:5wC!wnD#\KK^-'

DATABASE_LOGIN = 'db_admin'
DATABASE_PASSWORD = '*kau>FS8Nvu>bM#R'
DATABASE_HOST = 'localhost'
DATABASE_PORT = '5432'
DATABASE_NAME = 'kr'
